spring:
  profiles:
    active: local

springdoc:
  swagger-ui:
    path: /swagger
    url: ${swagger.ui.url}
    config-url: ${swagger.config.url}
  cache:
    disabled: true
  use-fqn: true

jwt:
  secret: ${jwt.secret}
  accessExpirationTime: ${jwt.expiration}
  refreshExpirationTime: ${jwt.refresh.expiration}

festival:
  api:
    key:
      decoded: ${festival.api.key.decoded}

#org:
#  neo4j:
#    driver:
#      uri:
#      authentication:
#        username:
#        password:

---

# local profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${local.db.url}
    username: ${local.db.username}
    password: ${local.db.password}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        use_sql_comments: true
        jdbc:
          batch_size: 10000
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

---

# develop profile
#spring:
#  config:
#    activate:
#      on-profile: develop
#  datasource:
#    url: ${aws.db.url}
#    username: ${aws.db.username}
#    password: ${aws.db.password}
#    driver-class-name: org.postgresql.Driver
#  sql:
#    init:
#      mode: never
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          batch_size: 10000
#        order_inserts: true
#        order_updates: true
#        use_sql_comments: true
#        hbm2ddl:
#          auto: update
#        default_batch_fetch_size: 1000
#
#logging:
#  level:
#    com.zaxxer.hikari: DEBUG
#    org.springframework.boot.autoconfigure.jdbc: DEBUG