spring:
  profiles:
    active: local
  jackson:
    time-zone: Asia/Seoul

springdoc:
  swagger-ui:
    path: /swagger
    url: ${swagger.ui.url}
    config-url: ${swagger.config.url}
  cache:
    disabled: true
  use-fqn: true

jwt:
  secret: ${jwt.secret}
  accessExpirationTime: ${jwt.expiration}
  refreshExpirationTime: ${jwt.refresh.expiration}

activity:
  api:
    key:
      festival: ${activity.api.key.festival}

neo4j:
  uri: ${neo4j.uri}
  authentication:
    username: ${neo4j.authentication.username}
    password: ${neo4j.authentication.password}

logging:
  level:
    org.springframework.batch: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG

kakaopay:
  secret_key: ${kakao.secret.key}
  cid: ${kakao.cid}

kakao:
  client_id: ${kakao.client.id}
---

# local profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${local.db.url}
    username: ${local.db.username}
    password: ${local.db.password}
    driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        use_sql_comments: true
        jdbc:
          batch_size: 10000
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
